import 'package:meta/meta.dart';

import '../common/copy_with_sentinel.dart';
import '../common/json_helpers.dart';

/// Audio attached to an assistant message.
///
/// [ChatAudioReference] is an ID-only reference for conversation replay.
/// [ChatCompletionAudio] retains complete generated audio, its transcript,
/// and expiry. Request serialization projects either variant to its ID.
@immutable
sealed class ChatAudio {
  const ChatAudio();

  /// Creates an ID-only audio reference for conversation replay.
  const factory ChatAudio.reference({required String id}) = ChatAudioReference;

  /// Creates complete generated audio.
  const factory ChatAudio.completion({
    required String id,
    required String data,
    required String transcript,
    required int expiresAt,
  }) = ChatCompletionAudio;

  /// Parses an ID-only reference or a complete audio object.
  ///
  /// Presence of any complete-output member requires all complete fields.
  factory ChatAudio.fromJson(Map<String, dynamic> json) =>
      json.containsKey('data') ||
          json.containsKey('transcript') ||
          json.containsKey('expires_at')
      ? ChatCompletionAudio.fromJson(json)
      : ChatAudioReference.fromJson(json);

  /// The identifier used to replay this audio in a later request.
  String get id;

  /// Converts this variant to its complete model representation.
  Map<String, dynamic> toJson();
}

/// An ID-only audio reference sent in an assistant message.
@immutable
class ChatAudioReference extends ChatAudio {
  /// Creates an audio reference.
  const ChatAudioReference({required this.id});

  /// Creates an audio reference from JSON.
  factory ChatAudioReference.fromJson(Map<String, dynamic> json) =>
      ChatAudioReference(
        id: requireJsonString(json['id'], 'ChatAudioReference.id'),
      );

  @override
  final String id;

  @override
  Map<String, dynamic> toJson() => {'id': id};

  /// Creates a copy with a replaced identifier.
  ChatAudioReference copyWith({String? id}) =>
      ChatAudioReference(id: id ?? this.id);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatAudioReference &&
          runtimeType == other.runtimeType &&
          id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'ChatAudioReference(id: [REDACTED])';
}

/// Complete audio generated by a Chat Completions response.
@immutable
class ChatCompletionAudio extends ChatAudio {
  /// Creates complete generated audio.
  const ChatCompletionAudio({
    required this.id,
    required this.data,
    required this.transcript,
    required this.expiresAt,
  });

  /// Creates complete generated audio, requiring every output member.
  factory ChatCompletionAudio.fromJson(Map<String, dynamic> json) =>
      ChatCompletionAudio(
        id: requireJsonString(json['id'], 'ChatCompletionAudio.id'),
        data: requireJsonString(json['data'], 'ChatCompletionAudio.data'),
        transcript: requireJsonString(
          json['transcript'],
          'ChatCompletionAudio.transcript',
        ),
        expiresAt: requireJsonInt(
          json['expires_at'],
          'ChatCompletionAudio.expires_at',
        ),
      );

  @override
  final String id;

  /// Base64 encoded audio bytes in the requested output format.
  final String data;

  /// The transcript of the generated audio.
  final String transcript;

  /// Unix timestamp when this audio is no longer available for replay.
  final int expiresAt;

  @override
  Map<String, dynamic> toJson() => {
    'id': id,
    'data': data,
    'transcript': transcript,
    'expires_at': expiresAt,
  };

  /// Creates a copy with replaced output members.
  ChatCompletionAudio copyWith({
    String? id,
    String? data,
    String? transcript,
    int? expiresAt,
  }) => ChatCompletionAudio(
    id: id ?? this.id,
    data: data ?? this.data,
    transcript: transcript ?? this.transcript,
    expiresAt: expiresAt ?? this.expiresAt,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatCompletionAudio &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          data == other.data &&
          transcript == other.transcript &&
          expiresAt == other.expiresAt;

  @override
  int get hashCode => Object.hash(id, data, transcript, expiresAt);

  @override
  String toString() =>
      'ChatCompletionAudio(id: [REDACTED], data: ${data.length} chars, '
      'transcript: ${transcript.length} chars, expiresAt: $expiresAt)';
}

/// Independently optional fields from a streamed audio update.
///
/// Empty strings and zero expiry are supplied values. Parsed members reject
/// explicit null; nullable constructor and copy values represent omission.
@immutable
class ChatAudioDelta {
  /// Creates a partial audio update.
  const ChatAudioDelta({this.id, this.data, this.transcript, this.expiresAt});

  /// Creates a partial update without inventing missing output members.
  factory ChatAudioDelta.fromJson(Map<String, dynamic> json) => ChatAudioDelta(
    id: optionalJsonString(json, 'id', 'ChatAudioDelta'),
    data: optionalJsonString(json, 'data', 'ChatAudioDelta'),
    transcript: optionalJsonString(json, 'transcript', 'ChatAudioDelta'),
    expiresAt: optionalJsonInt(json, 'expires_at', 'ChatAudioDelta'),
  );

  /// The audio identifier, when supplied by this update.
  final String? id;

  /// Opaque base64 audio data supplied by this update.
  final String? data;

  /// Transcript text supplied by this update.
  final String? transcript;

  /// Expiry timestamp, when supplied by this update.
  final int? expiresAt;

  /// Whether every required complete-output member is present.
  bool get isComplete =>
      id != null && data != null && transcript != null && expiresAt != null;

  /// Converts a complete snapshot to response audio.
  ///
  /// Throws [StateError] when any required output member is absent.
  ChatCompletionAudio toCompleteAudio() {
    if (!isComplete) {
      throw StateError(
        'ChatAudioDelta is incomplete; all audio fields are required.',
      );
    }
    return ChatCompletionAudio(
      id: id!,
      data: data!,
      transcript: transcript!,
      expiresAt: expiresAt!,
    );
  }

  /// Converts only the supplied members to JSON.
  Map<String, dynamic> toJson() => {
    if (id != null) 'id': id,
    if (data != null) 'data': data,
    if (transcript != null) 'transcript': transcript,
    if (expiresAt != null) 'expires_at': expiresAt,
  };

  /// Creates a copy; nullable members can be explicitly cleared.
  ChatAudioDelta copyWith({
    Object? id = unsetCopyWithValue,
    Object? data = unsetCopyWithValue,
    Object? transcript = unsetCopyWithValue,
    Object? expiresAt = unsetCopyWithValue,
  }) => ChatAudioDelta(
    id: id == unsetCopyWithValue ? this.id : id as String?,
    data: data == unsetCopyWithValue ? this.data : data as String?,
    transcript: transcript == unsetCopyWithValue
        ? this.transcript
        : transcript as String?,
    expiresAt: expiresAt == unsetCopyWithValue
        ? this.expiresAt
        : expiresAt as int?,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatAudioDelta &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          data == other.data &&
          transcript == other.transcript &&
          expiresAt == other.expiresAt;

  @override
  int get hashCode => Object.hash(id, data, transcript, expiresAt);

  @override
  String toString() =>
      'ChatAudioDelta(id: ${id == null ? 'null' : '[REDACTED]'}, '
      'data: ${_textSummary(data)}, transcript: ${_textSummary(transcript)}, '
      'expiresAt: $expiresAt)';
}

String _textSummary(String? value) =>
    value == null ? 'null' : '${value.length} chars';
