import 'package:meta/meta.dart';

import 'function_call.dart';

/// A tool call generated by the model.
@immutable
class ToolCall {
  /// The ID of the tool call.
  final String id;

  /// The type of tool call. Currently only 'function' is supported.
  final String type;

  /// The function call details.
  final FunctionCall function;

  /// The index of this tool call in a streaming response.
  ///
  /// Mistral uses this value to correlate deltas for parallel tool calls.
  final int? index;

  /// Creates a [ToolCall].
  const ToolCall({
    required this.id,
    this.type = 'function',
    required this.function,
    this.index,
  });

  /// Creates a [ToolCall] from JSON.
  factory ToolCall.fromJson(Map<String, dynamic> json) => ToolCall(
    id: json['id'] as String? ?? '',
    type: json['type'] as String? ?? 'function',
    function: FunctionCall.fromJson(
      json['function'] as Map<String, dynamic>? ?? {},
    ),
    index: json['index'] as int?,
  );

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    'id': id,
    'type': type,
    'function': function.toJson(),
    if (index != null) 'index': index,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolCall &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          function == other.function &&
          index == other.index;

  @override
  int get hashCode => Object.hash(id, type, function, index);

  @override
  String toString() =>
      'ToolCall(id: $id, type: $type, function: $function, index: $index)';
}
