import 'package:meta/meta.dart';

import '../common/copy_with_sentinel.dart';
import '../common/equality_helpers.dart';
import '../metadata/finish_reason.dart';
import '../tools/tool_call.dart';

/// A choice delta in a streaming chat completion response.
@immutable
class ChatChoiceDelta {
  /// The index of this choice in the list of choices.
  final int index;

  /// The delta content generated by the model.
  final DeltaContent delta;

  /// The reason the model stopped generating (only in final chunk).
  final FinishReason? finishReason;

  /// Creates a [ChatChoiceDelta].
  const ChatChoiceDelta({
    required this.index,
    required this.delta,
    this.finishReason,
  });

  /// Creates a [ChatChoiceDelta] from JSON.
  factory ChatChoiceDelta.fromJson(Map<String, dynamic> json) =>
      ChatChoiceDelta(
        index: json['index'] as int? ?? 0,
        delta: DeltaContent.fromJson(
          json['delta'] as Map<String, dynamic>? ?? {},
        ),
        finishReason: finishReasonFromString(json['finish_reason'] as String?),
      );

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    'index': index,
    'delta': delta.toJson(),
    if (finishReason != null)
      'finish_reason': finishReasonToString(finishReason!),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChoiceDelta &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          delta == other.delta &&
          finishReason == other.finishReason;

  @override
  int get hashCode => Object.hash(index, delta, finishReason);

  @override
  String toString() =>
      'ChatChoiceDelta(index: $index, delta: $delta, '
      'finishReason: $finishReason)';
}

/// Delta content in a streaming response.
@immutable
class DeltaContent {
  /// The role of the message (usually only in first chunk).
  final String? role;

  /// The content delta.
  final String? content;

  /// Tool calls delta.
  final List<ToolCall>? toolCalls;

  /// The ID of the tool call this delta responds to.
  final String? toolCallId;

  /// The index of this message.
  final int? index;

  /// Additional metadata attached to the message.
  final Map<String, dynamic>? metadata;

  /// Creates a [DeltaContent].
  const DeltaContent({
    this.role,
    this.content,
    this.toolCalls,
    this.toolCallId,
    this.index,
    this.metadata,
  });

  /// Creates a [DeltaContent] from JSON.
  factory DeltaContent.fromJson(Map<String, dynamic> json) => DeltaContent(
    role: json['role'] as String?,
    content: json['content'] as String?,
    toolCalls: (json['tool_calls'] as List?)
        ?.map((e) => ToolCall.fromJson(e as Map<String, dynamic>))
        .toList(),
    toolCallId: json['tool_call_id'] as String?,
    index: json['index'] as int?,
    metadata: json['metadata'] as Map<String, dynamic>?,
  );

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    if (role != null) 'role': role,
    if (content != null) 'content': content,
    if (toolCalls != null)
      'tool_calls': toolCalls!.map((e) => e.toJson()).toList(),
    if (toolCallId != null) 'tool_call_id': toolCallId,
    if (index != null) 'index': index,
    if (metadata != null) 'metadata': metadata,
  };

  /// Creates a copy with replaced values.
  DeltaContent copyWith({
    Object? role = unsetCopyWithValue,
    Object? content = unsetCopyWithValue,
    Object? toolCalls = unsetCopyWithValue,
    Object? toolCallId = unsetCopyWithValue,
    Object? index = unsetCopyWithValue,
    Object? metadata = unsetCopyWithValue,
  }) => DeltaContent(
    role: role == unsetCopyWithValue ? this.role : role as String?,
    content: content == unsetCopyWithValue ? this.content : content as String?,
    toolCalls: toolCalls == unsetCopyWithValue
        ? this.toolCalls
        : toolCalls as List<ToolCall>?,
    toolCallId: toolCallId == unsetCopyWithValue
        ? this.toolCallId
        : toolCallId as String?,
    index: index == unsetCopyWithValue ? this.index : index as int?,
    metadata: metadata == unsetCopyWithValue
        ? this.metadata
        : metadata as Map<String, dynamic>?,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeltaContent &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content &&
          listsEqual(toolCalls, other.toolCalls) &&
          toolCallId == other.toolCallId &&
          index == other.index &&
          mapsDeepEqual(metadata, other.metadata);

  @override
  int get hashCode => Object.hash(
    role,
    content,
    listHash(toolCalls),
    toolCallId,
    index,
    mapDeepHashCode(metadata),
  );

  @override
  String toString() =>
      'DeltaContent(role: $role, content: $content, toolCalls: $toolCalls, '
      'toolCallId: $toolCallId, index: $index, metadata: $metadata)';
}
