import 'package:meta/meta.dart';

import '../common/copy_with_sentinel.dart';
import '../common/equality_helpers.dart';
import '../metadata/finish_reason.dart';
import 'chat_choice_delta.dart';
import 'chat_message.dart';

/// A choice in a chat completion response.
@immutable
class ChatChoice {
  /// The index of this choice in the list of choices.
  final int index;

  /// The message generated by the model.
  ///
  /// May be `null` when the response uses [messages] instead.
  final AssistantMessage? message;

  /// The messages generated by the model.
  ///
  /// Present on responses that return multiple message deltas instead of a
  /// single [message].
  final List<DeltaContent>? messages;

  /// The reason the model stopped generating.
  final FinishReason finishReason;

  /// Creates a [ChatChoice].
  const ChatChoice({
    required this.index,
    this.message,
    this.messages,
    this.finishReason = FinishReason.unknown,
  });

  /// Creates a [ChatChoice] from JSON.
  factory ChatChoice.fromJson(Map<String, dynamic> json) => ChatChoice(
    index: json['index'] as int? ?? 0,
    message: json['message'] == null
        ? null
        : AssistantMessage.fromJson(json['message'] as Map<String, dynamic>),
    messages: (json['messages'] as List?)
        ?.map((e) => DeltaContent.fromJson(e as Map<String, dynamic>))
        .toList(),
    finishReason:
        finishReasonFromString(json['finish_reason'] as String?) ??
        FinishReason.unknown,
  );

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    'index': index,
    if (message != null) 'message': message!.toJson(),
    if (messages != null) 'messages': messages!.map((e) => e.toJson()).toList(),
    'finish_reason': finishReasonToString(finishReason),
  };

  /// Creates a copy with replaced values.
  ChatChoice copyWith({
    int? index,
    Object? message = unsetCopyWithValue,
    Object? messages = unsetCopyWithValue,
    FinishReason? finishReason,
  }) => ChatChoice(
    index: index ?? this.index,
    message: message == unsetCopyWithValue
        ? this.message
        : message as AssistantMessage?,
    messages: messages == unsetCopyWithValue
        ? this.messages
        : messages as List<DeltaContent>?,
    finishReason: finishReason ?? this.finishReason,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChoice &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          message == other.message &&
          listsEqual(messages, other.messages) &&
          finishReason == other.finishReason;

  @override
  int get hashCode =>
      Object.hash(index, message, listHash(messages), finishReason);

  @override
  String toString() =>
      'ChatChoice(index: $index, message: $message, '
      'messages: ${messages?.length ?? 'null'}, finishReason: $finishReason)';
}
