part of 'steps.dart';

/// A model-output step.
///
/// Represents output generated by the model, typically containing media-only
/// [InteractionContent] items (text, image, audio, document, video).
class ModelOutputStep extends InteractionStep {
  @override
  String get type => 'model_output';

  /// The content of the model output.
  final List<InteractionContent>? content;

  /// Creates a [ModelOutputStep] instance.
  const ModelOutputStep({this.content});

  /// Creates a [ModelOutputStep] from JSON.
  factory ModelOutputStep.fromJson(Map<String, dynamic> json) {
    if (json['type'] != 'model_output') {
      throw FormatException(
        'Expected type "model_output" but got "${json['type']}"',
      );
    }
    return ModelOutputStep(
      content: (json['content'] as List<dynamic>?)
          ?.map((e) => InteractionContent.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': type,
    if (content != null) 'content': content!.map((e) => e.toJson()).toList(),
  };

  /// Creates a copy with replaced values.
  ModelOutputStep copyWith({Object? content = unsetCopyWithValue}) {
    return ModelOutputStep(
      content: content == unsetCopyWithValue
          ? this.content
          : content as List<InteractionContent>?,
    );
  }
}
