part of 'steps.dart';

/// A model-output step.
///
/// Represents output generated by the model, typically containing media-only
/// [InteractionContent] items (text, image, audio, document, video).
class ModelOutputStep extends InteractionStep {
  @override
  String get type => 'model_output';

  /// The content of the model output.
  final List<InteractionContent>? content;

  /// The error result of the operation in case of failure or cancellation.
  final Status? error;

  /// Creates a [ModelOutputStep] instance.
  const ModelOutputStep({this.content, this.error});

  /// Creates a [ModelOutputStep] from JSON.
  factory ModelOutputStep.fromJson(Map<String, dynamic> json) {
    if (json['type'] != 'model_output') {
      throw FormatException(
        'Expected type "model_output" but got "${json['type']}"',
      );
    }
    return ModelOutputStep(
      content: (json['content'] as List<dynamic>?)
          ?.map((e) => InteractionContent.fromJson(e as Map<String, dynamic>))
          .toList(),
      error: json['error'] != null
          ? Status.fromJson(json['error'] as Map<String, dynamic>)
          : null,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': type,
    if (content != null) 'content': content!.map((e) => e.toJson()).toList(),
    if (error != null) 'error': error!.toJson(),
  };

  /// Creates a copy with replaced values.
  ModelOutputStep copyWith({
    Object? content = unsetCopyWithValue,
    Object? error = unsetCopyWithValue,
  }) {
    return ModelOutputStep(
      content: content == unsetCopyWithValue
          ? this.content
          : content as List<InteractionContent>?,
      error: error == unsetCopyWithValue ? this.error : error as Status?,
    );
  }
}
