import 'package:meta/meta.dart';

import '../common/copy_with_sentinel.dart';
import '../content/content_block.dart';
import '../metadata/stop_reason.dart';
import '../metadata/usage.dart';

/// A message response from the API.
@immutable
class Message {
  /// Unique object identifier.
  final String id;

  /// Object type. Always "message".
  final String type;

  /// Conversational role. Always "assistant".
  final String role;

  /// Content generated by the model.
  final List<ContentBlock> content;

  /// The model that handled the request.
  final String model;

  /// The reason the model stopped generating.
  final StopReason? stopReason;

  /// The stop sequence that caused generation to stop, if any.
  final String? stopSequence;

  /// Token usage statistics.
  final Usage usage;

  /// Creates a [Message].
  const Message({
    required this.id,
    this.type = 'message',
    this.role = 'assistant',
    required this.content,
    required this.model,
    this.stopReason,
    this.stopSequence,
    required this.usage,
  });

  /// Creates a [Message] from JSON.
  factory Message.fromJson(Map<String, dynamic> json) {
    return Message(
      id: json['id'] as String,
      type: json['type'] as String? ?? 'message',
      role: json['role'] as String? ?? 'assistant',
      content: (json['content'] as List)
          .map((e) => ContentBlock.fromJson(e as Map<String, dynamic>))
          .toList(),
      model: json['model'] as String,
      stopReason: json['stop_reason'] != null
          ? StopReason.fromJson(json['stop_reason'] as String)
          : null,
      stopSequence: json['stop_sequence'] as String?,
      usage: Usage.fromJson(json['usage'] as Map<String, dynamic>),
    );
  }

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    'id': id,
    'type': type,
    'role': role,
    'content': content.map((e) => e.toJson()).toList(),
    'model': model,
    if (stopReason != null) 'stop_reason': stopReason!.toJson(),
    if (stopSequence != null) 'stop_sequence': stopSequence,
    'usage': usage.toJson(),
  };

  /// Creates a copy with replaced values.
  Message copyWith({
    String? id,
    String? type,
    String? role,
    List<ContentBlock>? content,
    String? model,
    Object? stopReason = unsetCopyWithValue,
    Object? stopSequence = unsetCopyWithValue,
    Usage? usage,
  }) {
    return Message(
      id: id ?? this.id,
      type: type ?? this.type,
      role: role ?? this.role,
      content: content ?? this.content,
      model: model ?? this.model,
      stopReason: stopReason == unsetCopyWithValue
          ? this.stopReason
          : stopReason as StopReason?,
      stopSequence: stopSequence == unsetCopyWithValue
          ? this.stopSequence
          : stopSequence as String?,
      usage: usage ?? this.usage,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          role == other.role &&
          _listsEqual(content, other.content) &&
          model == other.model &&
          stopReason == other.stopReason &&
          stopSequence == other.stopSequence &&
          usage == other.usage;

  @override
  int get hashCode => Object.hash(
    id,
    type,
    role,
    content,
    model,
    stopReason,
    stopSequence,
    usage,
  );

  @override
  String toString() =>
      'Message(id: $id, type: $type, role: $role, '
      'content: $content, model: $model, stopReason: $stopReason, '
      'stopSequence: $stopSequence, usage: $usage)';
}

bool _listsEqual<T>(List<T>? a, List<T>? b) {
  if (a == null && b == null) return true;
  if (a == null || b == null) return false;
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
