// Golden receipts independently generated by Python hmac/hashlib.
// The official vector also appears verbatim in both official SDK tests.
const verifierVectors = <String, Map<String, Object>>{
  'official': {
    'body':
        '{"id": "evt_685c059ae3a481909bdc86819b066fb6", "object": "event", "created_at": 1750861210, "type": "response.completed", "data": {"id": "resp_123"}}',
    'id': 'wh_685c059ae39c8190af8c71ed1022a24d',
    'timestamp': '1750861210',
    'signature': 'gUAg4R2hWouRZqRQG4uJypNS8YK885G838+EHb4nKBY=',
  },
  'unicode': {
    'body': '{"type":"future.event","message":"café 🦉 é","line":"x\\n"}\r\n',
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': 'szhNyae//iybNsl5kTholO7YGsk/s6jNSgcctbIlvOw=',
  },
  'bom': {
    'body': '﻿  {"type":"future.event","data":{}}\n',
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': 'aBRoSZHR7GXwQ/n2433HP2TQ40Q62xRnBaA4gBW6iVY=',
  },
  'invalidJson': {
    'body': 'SENSITIVE_BODY non-JSON café',
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': 'IhVAMbqKzjSPtRPI36+50Ynf2F4maf8DC2hk4sYGzdI=',
  },
  'invalidUtf8': {
    'bytes': [255, 254, 0, 127],
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': 'NQhZXAkwT3h7Jdu1V8MoK1YkN9HcxVixyxxK3V1PFAw=',
  },
  'malformedJson': {
    'body': '{"SENSITIVE_BODY":',
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': 'IHyKPo2HHrbPyHMWV58hzPVD4kwVxyW33YbCkkRDRLM=',
  },
  'knownMalformed': {
    'body':
        '{"id":"SENSITIVE_BODY","type":"response.completed","created_at":1,"data":{"id":null}}',
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': '8FHqP1N5vgqSTJmP1bM0TI4HaOB//awWyuqpJzEJkt8=',
  },
  'array': {
    'body': '["SENSITIVE_BODY"]',
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': '6NNrTrp1pHLNR7pfq8sGE0OkwbAwr8U8+n26BBrCWVA=',
  },
  'nonfinite': {
    'body': '{"type":"future.event","SENSITIVE_BODY":1e309}',
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': '269vmlQUgUhC7ctFlUSLDmtFK9aCql18iV9AVfpmVq4=',
  },
  'leadingZero': {
    'body': '{}',
    'timestamp': '0001750861210',
    'id': 'delivery',
    'signature': 'iQxcV/nJcokMIqEGRtIIo6SHjiXyOfBpohCM7xJULv4=',
  },
  'zero': {
    'body': '{}',
    'timestamp': '0',
    'id': 'delivery',
    'signature': 'jdaTTgBwLPY05yGQ0JXk2CAF77d0UbBVoSnlGy0BCD0=',
  },
  'safeMaximum': {
    'body': '{}',
    'timestamp': '9007199254740991',
    'id': 'delivery',
    'signature': 'COhwDnPWUeMGACnH7ghdbbyVy5vTJhmEfXPaS2NPBHA=',
  },
  'safeMaximumLeading': {
    'body': '{}',
    'timestamp': '0009007199254740991',
    'id': 'delivery',
    'signature': 'BvgcuRCNw0Uh0PApDX/bKUuhUafNQ4nViE9aVs7MqtQ=',
  },
  'pastBoundary': {
    'body': '{}',
    'timestamp': '1750860910',
    'id': 'delivery',
    'signature': '4ewD7CoQMpXlfT5SCwhtAbYAUhnW6NkuOIfQNbWe+Zk=',
  },
  'futureBoundary': {
    'body': '{}',
    'timestamp': '1750861510',
    'id': 'delivery',
    'signature': 'UfeiYKAwiS4RSwQN/RReoddLzaI1xAjKXTQiTPp5jfg=',
  },
  'pastSecond': {
    'body': '{}',
    'timestamp': '1750861209',
    'id': 'delivery',
    'signature': 'wwTXIZ8khi4cdIKK1wwPWG34nxYCPnH+GklBHEL7PL8=',
  },
  'futureSecond': {
    'body': '{}',
    'timestamp': '1750861211',
    'id': 'delivery',
    'signature': 'TX5rpPY15L7cfkJRDtQUCv0WEg5xYQivdXNQp562U44=',
  },
  'dotsId': {
    'body': '{}',
    'id': '.prefix.ID..雪\nsuffix.',
    'timestamp': '1750861210',
    'signature': '6qjH78knG4rgD2FNoeYMQRYK3c/rlqjm8CGaRmepvRI=',
  },
  'spaceId': {
    'body': '{}',
    'id': ' ',
    'timestamp': '1750861210',
    'signature': '5cvCK3qENrlIQmgzlL4CQPGAzZ2DEMkZK3Hbk513Sk8=',
  },
  'literalBase64Key': {
    'body': '{}',
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': 'nTSb6UYXRZr9QtdD/Uso+qaySBibWRDzkoMiRbMUIEw=',
  },
  'unicodeKey': {
    'body': '{}',
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': 'DRONgWQAijhDctnoRaYR41JhrCj9CEb5uI4890Cx088=',
  },
  'largeBody': {
    'bytesLength': 2097152,
    'byteValue': 97,
    'timestamp': '1750861210',
    'id': 'delivery',
    'signature': 'BzezpxUxau0MkZcNlkvrxdz2dHIrB3ukiFaKP7dFH5c=',
  },
};
