// ignore_for_file: avoid_print
/// Example demonstrating content provenance checks with OpenAI.
///
/// The Content Provenance Checks API detects OpenAI C2PA and SynthID
/// provenance signals in an uploaded image or audio file — useful for
/// verifying whether content was generated by an OpenAI model.
///
/// Run with: dart run example/content_provenance_checks_example.dart
library;

import 'dart:convert';

import 'package:openai_dart/openai_dart.dart';

Future<void> main() async {
  // Create client from environment variable
  final client = OpenAIClient.fromEnvironment();

  try {
    // Generate an image so we have OpenAI-produced content to check.
    print('=== Generate Image ===\n');

    final generated = await client.images.generate(
      const ImageGenerationRequest(
        model: ImageModels.gptImage2,
        prompt: 'A watercolor painting of a lighthouse at sunset',
        size: ImageSize.size1024x1024,
      ),
    );

    final b64Json = generated.data.first.b64Json!;
    final imageBytes = base64Decode(b64Json);
    print('Generated ${imageBytes.length} bytes\n');

    // Check the generated image for provenance signals.
    print('=== Content Provenance Check ===\n');

    final check = await client.contentProvenanceChecks.create(
      bytes: imageBytes,
      filename: 'lighthouse.png',
    );

    print('Object: ${check.object}');
    print('Created at: ${check.createdAt}');
    print('Signals found: ${check.results.length}\n');

    for (final result in check.results) {
      switch (result) {
        case C2PAProvenanceResult():
          print('C2PA signal:');
          print('  Outcome: ${result.outcome}');
          print('  Validation state: ${result.validationState}');
          print('  Model: ${result.model ?? 'unknown'}');
          print('  Issuer: ${result.issuer ?? 'unknown'}');
          print('  Generated at: ${result.generatedAt ?? 'unknown'}');
        case SynthIDProvenanceResult():
          print('SynthID signal:');
          print('  Outcome: ${result.outcome}');
          print('  Model: ${result.model ?? 'unknown'}');
          print('  Generated at: ${result.generatedAt ?? 'unknown'}');
        case UnknownProvenanceResult():
          print('Unrecognized signal type: ${result.type}');
      }
    }
  } on OpenAIException catch (e) {
    print('OpenAI error: ${e.message}');
    if (e is ApiException) {
      print('Status: ${e.statusCode}');
    }
  } finally {
    client.close();
    print('\nDone!');
  }
}
